//Problem 2

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Euler
{
    class Euler2
    {
        public static void euler_2()
        {
            int n1 = 1;
            int n2 = 1;
            int term = 1;
            int sum = 0;
            int top = 4000000;
            List<int> list = new List<int>();

            while (term < top)
            {

                if (term % 2 == 0)
                {

                    sum = sum + term;
                    list.Add(term);
                }

                term = n1 + n2;
                n1 = n2;
                n2 = term;
                //Console.WriteLine("term: {0}, n1: {1}, n: {2}", term, n1, n2);
            }
            Console.WriteLine(sum);
            foreach (var item in list)
            {
                //Console.WriteLine("even term in sequence: {0}", item);

            }
            Console.ReadLine();
        }
    }
}
